repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: Pytest
        entry: python -m pytest
        language: python
        pass_filenames: false
        additional_dependencies:
          - pytest